//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.gitonway.fineday.interfaces.impl;

import android.content.Context;

public final class WeaterFinderImpl_
    extends WeaterFinderImpl
{

    private Context context_;

    private WeaterFinderImpl_(Context context) {
        context_ = context;
        init_();
    }

    public static WeaterFinderImpl_ getInstance_(Context context) {
        return new WeaterFinderImpl_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
