//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.gitonway.fineday.domain;

import android.content.Context;

public final class WeaterLogic_
    extends WeaterLogic
{

    private Context context_;

    private WeaterLogic_(Context context) {
        context_ = context;
        init_();
    }

    public static WeaterLogic_ getInstance_(Context context) {
        return new WeaterLogic_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
