//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.gitonway.fineday.adapter;

import android.content.Context;

public final class MyCityAapter_
    extends MyCityAapter
{

    private Context context_;

    private MyCityAapter_(Context context) {
        context_ = context;
        init_();
    }

    public static MyCityAapter_ getInstance_(Context context) {
        return new MyCityAapter_(context);
    }

    private void init_() {
        context = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
