//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.gitonway.fineday.adapter;

import android.content.Context;

public final class WeaterAdapter_
    extends WeaterAdapter
{

    private Context context_;

    private WeaterAdapter_(Context context) {
        context_ = context;
        init_();
    }

    public static WeaterAdapter_ getInstance_(Context context) {
        return new WeaterAdapter_(context);
    }

    private void init_() {
        context = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
